---
# tasks file for enabling epel and nodejs

- name: Enabling EPEL
  shell: "amazon-linux-extras install epel -y"

- name: Installing node and npm
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: installed
  with_items:
    - nodejs
    - npm
